/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffd9de",
        "background": "#f8f9ff",
        "primary-fixed": "#7ffc97",
        "on-secondary-fixed": "#00174b",
        "secondary-fixed-dim": "#b4c5ff",
        "primary-fixed-dim": "#62df7d",
        "surface-container-highest": "#d3e4fe",
        "outline": "#6e7b6c",
        "secondary-container": "#316bf3",
        "outline-variant": "#bdcaba",
        "on-primary-fixed": "#002109",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "secondary": "#0051d5",
        "primary": "#006b2c",
        "surface-tint": "#006e2d",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "inverse-primary": "#62df7d",
        "on-secondary-container": "#fefcff",
        "primary-container": "#00873a",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed-variant": "#8a143c",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#3e4a3d",
        "surface-container": "#e5eeff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8f9ff",
        "tertiary-container": "#c74668",
        "surface": "#f8f9ff",
        "tertiary-fixed-dim": "#ffb2bf",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#005320",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#3f0016",
        "on-secondary-fixed-variant": "#003ea8",
        "on-secondary": "#ffffff",
        "tertiary": "#a72d51",
        "on-primary-container": "#f7fff2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "stack-sm": "8px",
        "stack-lg": "24px",
        "gutter": "12px",
        "container-padding": "20px",
        "stack-md": "16px"
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "stat-label": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-financial": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
